# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Danggeun_Clone' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Firebase/Auth'
  pod 'Firebase/Analytics'
  pod 'Firebase/Firestore'
  pod "BSImagePicker", "~> 3.1"
  pod 'Firebase/Storage'
  pod ‘Kingfisher’, ‘~> 5.0’ 
  pod 'SnapKit'

  # Pods for Danggeun_Clone

end
